# Generated by Django 3.2 on 2023-01-17 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compositions', '0003_auto_20230117_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
