# Generated by Django 3.2 on 2023-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0004_alter_composition_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Label',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='tags',
        ),
        migrations.AddField(
            model_name='composition',
            name='labels',
            field=models.ManyToManyField(blank=True, to='compositions.Label'),
        ),
    ]
