# Generated by Django 3.2 on 2023-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0006_auto_20230117_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='comp_image',
            field=models.ImageField(blank=True, default='hero.png', null=True, upload_to=''),
        ),
    ]
