# Generated by Django 3.2 on 2023-01-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0007_composition_comp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='comp_link',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
