# Generated by Django 3.2 on 2023-01-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0008_composition_comp_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
