# Generated by Django 3.2 on 2023-01-18 19:24

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('compositions', '0011_auto_20230118_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='comp_link',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='site_link',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='compositions.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
