# Generated by Django 3.2 on 2023-01-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0012_auto_20230118_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='comp_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='site_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
