# Generated by Django 3.2 on 2023-01-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('compositions', '0013_auto_20230118_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
