# Generated by Django 3.2 on 2023-01-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0014_composition_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
