# Generated by Django 3.2 on 2023-01-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0015_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='status',
        ),
    ]
